### ISSUE TITLE
Unable to connect to chrome.

### ISSUE THREAD

**Issue by PawFV** [GoogleChrome/lighthouse-ci#802] opened 2022-06-08 01:35 UTC
**Describe the bug**
Similar to #761, and #799 with slightly different error in the end.

**Expected behavior**
Should collect analysis in github action.

**Logs/Screenshots**

![image](https://user-images.githubusercontent.com/44122984/172511316-68ec46b4-593c-4a53-98bf-41b1b9d4edab.png)

![image](https://user-images.githubusercontent.com/44122984/172511352-7fde5f0c-96c2-4c0a-875f-e5cf4f08cf0c.png)

**Environment (please complete the following information):**
 - Version 0.9.0

**Additional context**

I installed chrome in my github action to make the check "Chrome installation found", this way:
```sh
 run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
```

**Comment by paulirish** [comment] 2022-08-31 19:56
in configuration, you want to do ci.collect.settings.hostname of `127.0.0.1`

<img width="331" alt="image" src="https://user-images.githubusercontent.com/39191/187770262-c9ec5971-7c5d-419d-9409-fd91fe354e18.png">


Pretty sure that should sort it.  Apologies for this.

**Comment by paulirish** [comment] 2022-08-31 19:57
closing as dupe of #799closing as dupe of #799

**Closed by paulirish** 2022-08-31 19:57 UTC
