### ISSUE TITLE
GitHub statuses marked as failed when they pass

### ISSUE THREAD

**Issue by charlespwd** [GoogleChrome/lighthouse-ci#588] opened 2021-04-19 17:16 UTC
**Describe the bug**
With `assert.includePassedAssertions: true`, GitHub statuses on PR are marked as "failed" even when they pass.

I've narrowed down to the upload run command checking for error levels instead of if the assertion passed when preparing the github status messages.

When `assert.includePassedAssertions` is true, passed assertions are saved in .lighthouseci/assertion-results.json. So [`loadAssertionResults()`](https://github.com/GoogleChrome/lighthouse-ci/blob/main/packages/cli/src/upload/upload.js#L241) returns passed and failed assertions.

So the following [two lines](https://github.com/GoogleChrome/lighthouse-ci/blob/main/packages/cli/src/upload/upload.js#L250-L251):

```js
const failedResults = group.filter(result => result.level === 'error');
const warnResults = group.filter(result => result.level === 'warn');
```

should be the following:

```js
const failedResults = group.filter(result => result.level === 'error' && !result.passed);
const warnResults = group.filter(result => result.level === 'warn' && !result.passed);
```

**To Reproduce**
1. Setup a GitHub action with a `LHCI_GITHUB_TOKEN`
2. Use assertions with `includePassedAssertions: true`
3. Visit pages that pass the assertions

**Expected behavior**

1. GitHub status per URL is green.

**Actual behavior**

1. GitHub status per URL are red.

**More context**

Partial contents of .lighthouseci/assertion-results.json

```json
[
  {
    "name": "minScore",
    "expected": 0.9,
    "actual": 0.93,
    "values": [
      0.93,
      0.93,
      0.93
    ],
    "operator": ">=",
    "passed": true,
    "auditProperty": "performance",
    "auditId": "categories",
    "level": "error",
    "url": "https://example.com"
  }
]

**Comment by patrickhulce** [comment] 2021-04-19 17:31
thanks for filing @charlespwd! this is a duplicate of #570 and will be fixed by #575, we'll keep tracking over there

**Closed by patrickhulce** 2021-04-19 17:31 UTC
